const $=s=>document.querySelector(s);let near=false;
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw Error(j.because||j.error);return j}
const short=s=>(s||'—').slice(0,12);
function setSurface(name){$('#game-view').classList.toggle('active',name==='GAME');$('#carrier-view').classList.toggle('active',name==='CARRIER');$('#game-tab').classList.toggle('active',name==='GAME');$('#carrier-tab').classList.toggle('active',name==='CARRIER');$('#surface').textContent=name}
function pos(el,p){if(!p)return;el.style.left=`${50+p[0]*7}%`;el.style.top=`${55+p[1]*7}%`}
function carrier(view){const svg=$('#carrier-svg');svg.innerHTML='';const ns='http://www.w3.org/2000/svg',cells=view.cells,by={};cells.forEach((c,i)=>{const a=i/cells.length*Math.PI*2,x=600+260*Math.cos(a),y=330+230*Math.sin(a);by[c.cell_id]={x,y};const g=document.createElementNS(ns,'g');g.innerHTML=`<circle cx="${x}" cy="${y}" r="52" fill="#102022" stroke="${c.payload_phase==='EMPTY'?'#416064':'#53e3d8'}" stroke-width="2"/><text x="${x}" y="${y-5}" text-anchor="middle" fill="#dce9eb" font-size="13">${c.operator}</text><text x="${x}" y="${y+15}" text-anchor="middle" fill="#71888a" font-size="10">× ${c.witness}</text><text x="${x}" y="${y+72}" text-anchor="middle" fill="#53e3d8" font-size="9">${c.payload_phase}</text>`;svg.appendChild(g)});view.routes.forEach(r=>{const a=by[r.source_cell],b=by[r.target_cell];if(!a||!b)return;const l=document.createElementNS(ns,'line');l.setAttribute('x1',a.x);l.setAttribute('y1',a.y);l.setAttribute('x2',b.x);l.setAttribute('y2',b.y);l.setAttribute('stroke','#29484a');l.setAttribute('stroke-width','2');svg.insertBefore(l,svg.firstChild)})}
function draw(payload){const render=payload.last_render||payload,view=render.view||payload.view,surface=render.active_surface||payload.active_surface?.surface;setSurface(surface);if(view?.entities){const ents=Object.fromEntries(view.entities.map(e=>[e.entity_id,e]));pos($('#player'),ents.player.world_position);pos($('#enemy-01'),ents.enemy_01.world_position);pos($('#enemy-02'),ents.enemy_02.world_position);$('#behavior').textContent=view.behavior_status;$('#behavior').style.borderColor=view.behavior_status==='STALL'?'#ed5264':'#53e3d8'}if(view?.cells)carrier(view);const snap=payload.snapshot||{};$('#tick').textContent=`TICK ${snap.logical_tick_index??view?.logical_tick_index??0}`;$('#run-status').textContent=snap.run_status||view?.behavior_status||'READY';$('#snapshot').textContent=short(payload.snapshot_digest||view?.snapshot_digest);$('#run').textContent=short(snap.game_run_id);$('#fabric').textContent=short(snap.fabric_digest);$('#state').textContent=short(snap.fabric_state_digest);const phases=snap.committed_fabric_state?.payload_states||{};$('#phases').innerHTML=Object.entries(phases).map(([k,v])=>`<div class="phase ${v.phase}" title="${k}">${k}<br>${v.phase}</div>`).join('')}
async function refresh(){draw(await api('/api/state'))}
$('#game-tab').onclick=async()=>{if($('#surface').textContent!=='GAME')draw(await api('/api/toggle',{}))};$('#carrier-tab').onclick=async()=>{if($('#surface').textContent!=='CARRIER')draw(await api('/api/toggle',{}))};$('#near').onclick=()=>{near=!near;$('#near').textContent=near?'PLAYER NEAR':'PLAYER FAR'};$('#health').oninput=e=>$('#health-value').textContent=e.target.value;$('#advance').onclick=async()=>{await api('/api/game/controls',{player_near:near,enemy_health:Number($('#health').value)});draw(await api('/api/game/tick',{}))};$('#blocked').onclick=async()=>draw(await api('/api/game/blocked',{}));refresh();
